@startuml

|#pink|Usuário|
start

:Acessar o Aplicativo;

repeat 
:Realizar Login;

|#lightblue|Sistema Banco Itatiaia|

:Autenticar;
:Autorizar;

repeat while (autorizado?) is (não) not (sim)
:Liberar o acesso à tela principal do aplicativo;

|Usuário|

:Selecionar dados do cartão;

|Sistema Banco Itatiaia|

:Recuperar informações do cartão;
:Exibir dados do cartão;

|Usuário|

:Visualizar dados do cartão;

stop
@enduml
