@startuml

|#pink|Usuário|
start

:Acessar o Aplicativo;

repeat 
:Realizar Login;

|#lightblue|Sistema Banco Itatiaia|

:Autenticar;
:Autorizar;

repeat while (autotizado?) is (não) not (sim)
:Liberar o acesso à tela principal do aplicativo;

|Usuário|

:Selecionar extrato bancário;

|Sistema Banco Itatiaia|

:Recuperar extrato bancário;
:Exibir extrato bancário;

|Usuário|

:Solicitar comprovante de uma movimentação;

|Sistema Banco Itatiaia|
:Gerar comprovante de pagamento;

stop
@enduml
