@startuml

|#pink|Usuário|
start

:Acessar o Aplicativo;

repeat 
:Realizar Login;

|#lightblue|Sistema Banco Itatiaia|

:Autenticar;
:Autorizar;

repeat while (autotizado?) is (não) not (sim)
:Liberar o acesso à tela principal do aplicativo;

|Usuário|

:Selecionar pagamento de contas;

switch (Como identificar o boleto?)
case ( Escanear )
  :Escanear código de barras;
case ( digitar ) 
  :Digitar código;

endswitch

|Sistema Banco Itatiaia|

:Verificações de segurança;
:Verificações de regras de negócio;

:Apresentar resumo da operação;

|Usuário|

:Confirmar operação;

if (transação confirmada?) then (não)
end
else (sim)
|Sistema Banco Itatiaia|
:Concluir transação;
:Gerar comprovante de pagamento;

stop
@enduml
